### ISSUE TITLE
Difference to other plugin

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/netbeans-antlr#1]
Hi,

what will be the differences to this plugin: https://github.com/fredyvonvinet/ANTLR4-Plugins-for-NetBeans? Is this really needed? It would be better to help him to make the plugin better. I think he is pleased to see work from contributors :)

**Comment by mcheung63** [comment]
I think it is outdated, can't find it on plugin central. When i search antlr in plugin central, no plugin is for netbeans 8.2. I am developing an x86/arm assembler using antlr so want to enhance netbeans.

**Comment by Chris2011** [comment]
No it is not, as you can see it is up to date with some bugs. Maybe you can try to fix them too. No need to have 2 plugins, which make the same in the end. Last commit was 9 days ago. Some tickets open, from me too and lots of discussion. So no outdated. Plugin for 8.2 can be found inside the repo: http://plugins.netbeans.org/plugin/70625/antlr-4-plugin-for-netbeans-8

You can't see it, because they are not signed.

Great to here about your project :)

**Comment by mcheung63** [comment]
please submit the plugin to verification in plugin central, i can't search it out in the netbeans. Anyway i am installing it, thanks

**Comment by Chris2011** [comment]
I'm Not the author of the Plugin as you can See it in the repo. Please add a Ticket there.

**Comment by mcheung63** [comment]
thanks Chris. One last question, in eclipse world, many plugins are doing similar things such as subclipse and subversive are similar subversion plugin. In netbeans world, does the community agree to develop more plugin for users to choose?

**Comment by Chris2011** [comment]
Sure, it is up to me. But in my perspective it doesn't make sense. Because if we have a full featured plugin for example the ANTLR, why we need a second or a third one? Than you have bugs in that one, missing feature in this one and and and. Why would you will make your own a lot of work to create a plugin which is already there and has features which you not have to implement it by your own?. Make that ones better which are already there. This is more fun and needed. If there is smth not in in that plugin and you are willing to contribute, do it. There are a lot of open tickets, try to fix them please, no need to have a new, different one with differences.

**Comment by Chris2011** [comment]
I created an other ticket and asked for collaboration: https://github.com/fredyvonvinet/ANTLR4-Plugins-for-NetBeans/issues/46

**Comment by mcheung63** [comment]
Thanks everybody


________________________________
