### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by emilianbold** [mcheung63/netbeans-antlr#4]
Hello,

I see `licenseheader.txt` is empty.

Some files mention GPL v3 while I see commits where the GPL v3 header has been removed.

So -- what is the license of this project?

**Comment by mcheung63** [comment]
thanks for telling, updated the licenseheader.txt, it is GPLv3

**Comment by emilianbold** [comment]
I understand why you are using it, but note that GPLv3 is not compatible with the Apache license so this codebase will never be taken into consideration by Apache NetBeans.

**Comment by mcheung63** [comment]
let me change to apache license, anyway i don't care which license, i just want my source to be completely free to anybody :-)

**Comment by emilianbold** [comment]
Glad you feel this way. If you are curious about this stuff you could do some reading -- licensing is an interesting subject.

Apache 2.0 is a good choice but even the much simpler MIT license https://choosealicense.com/licenses/mit/ is very popular and Apache-compatible.

**Comment by mcheung63** [comment]
thanks Emilian
